[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-start-keep-alive",
  "allow-stop-keep-alive",
  "allow-is-keep-alive-running",
  "allow-request-battery-optimization",
  "allow-is-battery-optimization-ignored"
]
